id: P9B5E37C4
initial_creation_type: input
source_metadata:
  Title: ''
  Editor: Bhattacharyya, Beynotosh
  Publisher: The Oriental Institute
  Place of Publication: Baroda
  Year: '1942'
  तर्कभाषाटीका:
    Text Version: Devanagari
    Input Personnel: DSBC Staff
    Input Date: '2013'
    Proof Reader: Milan Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T16:59:45.368048'
last_modified_at: '2022-03-08T16:59:45.368056'
